# BSC 监控服务配置

# RPC 端点
rpc.endpoint=https://bsc-mainnet.nodereal.io/v1/9613675572f24988819d24233504b290

# 目标代币地址
token.address=0xfe930c2d63aed9b82fc4dbc801920dd2c1a3224f

# 代币创建区块号
token.creation.block=70418263

# 数据库配置
database.host=127.0.0.1
database.port=13306
database.name=monitor
database.username=root
database.password=cljslrl0620

# 是否从数据库加载历史数据
load.history.from.database=false

